### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by mgrush** [mgrush/mgrush#3]
### 报错内容

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/response.js:163:12)
    at Handlers.authorize (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/lib/route/index.js:14:15)
    at Layer.handle [as handle_request] (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/router/route.js:131:13)
    at next (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/router/route.js:125:14)
    at next (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/router/route.js:125:14)
    at next (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/router/route.js:125:14)
    at next (/home/www/yuquan.caimi-inc.com/node-mgrush.github.com/node_modules/express/lib/router/route.js:125:14)
```

**Comment by mgrush** [comment]
#### 问题描述

出现该问题的主要原因是因为服务器端已经完成过一次header头部信息的输出（比如：res.send、res.end等），然后在后面的代码中又重复的执行了一次header内容输出导致的。

#### 问题代码

在路由器的配置中，我为每一个路由匹配方法都添加了一个authorize方法作为filter，如下代码所示：

```
// 统一模块路由处理方法 /contName/funcName
app.all("/:contName/:funcName", Handlers.authorize, function(req, res, next){
    var contName    = req.params.contName;
    var funcName    = req.params.funcName;

    return next();

    Handlers.run(req, res, {
        contName    : contName,
        funcName    : funcName
    });
});
```

而在Handlers.authorize方法中，为了避免登陆限制对代码调试的影响，在if判断之前增加next()调用：

```
// 用户登录验证
authorize : function(req, res, next){
    next();

    if( loginWhiteList.indexOf(req.path) == -1 && !UserModel.authorize() ) {
        return res.send("请优先登录");
    }

    next();
}
```

所以，在调用测试接口的时候，显示之行了第一个next，然后在if判断中因为是为登录状态，重复之行了一次res.send方法，所以会出现这个问题。
